version: '3.8'
services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8443:80"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=
    command: python bot.py
